### ISSUE TITLE
`filesystem` Package

### ISSUE THREAD

**Issue by matthewchivers** [matthewchivers/dodl#10]
Develop the filesystem package, which handles file and directory operations. This package ensures that files are correctly written to disk.

## Responsibilities

* Ensure necessary directories exist.
* Write content to files.
* Handle file permissions and error handling.

## Implementation Details

* Use Go's os and io/ioutil packages for filesystem operations.
* Ensure that file writes are atomic if necessary.
* Handle any filesystem-related errors gracefully.

## Interactions

* Called by the Core Controller during document creation.
* Does not depend on other components.

## Tasks

- [x] Set up the filesystem package
- [x] Implement MkDir function
- [x] Implement WriteFile function

**Comment by matthewchivers** [comment]
This has been partially implemented in https://github.com/matthewchivers/dodl/pull/14

Setup and `MkDir` functionality

**Comment by matthewchivers** [comment]
File writing implemented here:

* https://github.com/matthewchivers/dodl/pull/15/

And then greatly improved here:
* https://github.com/matthewchivers/dodl/pull/18
