### ISSUE TITLE
[epic] Version 1.0.0 Roadmap: Enhanced Features and User Experience Improvements

### ISSUE THREAD

**Issue by matthewchivers** [matthewchivers/dodl#27]
## Overview

This epic outlines the key features and improvements planned for the `dodl` project leading up to the **`v1.0.0`** release. The focus is on enhancing usability, expanding functionality, and ensuring that configurations are easy to manage.

## Objectives / Milestones

- [ ] **Configuration Management**
- [ ] **Ability to Specify Values from the Command-Line**
- [ ] **Verbose and Debug Modes**
- [ ] **Natural Language Support For Dates**
- [ ] **Document Type Information**
- [ ] **User Experience Improvements**
- [x] **Version Command**
- [ ] **User Prompts** (optional, conflicts with original goal of running non-interactively, so requires thought)
- [ ] **History Command** (stretch goal, requires significant consideration)

> It _just so happens_ that there are 9 points here (not actually planned). So, going up the minor versions (`0.1.0`, `0.2.0`... `0.9.0`) gets us nicely to `1.0.0` once all these objectives are met.

### Configuration Management
- Configuration schema validation to enforce the structure of configuration files.
- Allow users to set configuration settings from the command-line.

### Ability to Specify Values from the Command-Line
- Allow users to specify values directly from the command-line, including document name or pattern, directory name or pattern, and other fields.

### Verbose and Debug Modes
- Verbose mode to provide additional information during command execution.
- Debug mode to output detailed debugging information, primarily aimed at developers.
- Logging improvements to enable these modes.

### Natural Language Support For Dates
- Natural language date parsing for specifying dates, such as "next Wednesday" or "in 3 days".

### Document Type Information
- List available document types and allow the user to get information on a specific document type.

### User Experience Improvements
- Command aliases to make common commands easier to use.

### Version Command
- Version command to display the current version of `dodl`.
- Integrate version information into the help output?

### User Prompts
- Interactive prompts when required fields are missing, allowing users to input values interactively.
    - Optional / needs some serious thought, as one of the original goals was to make dodl headless from the ground up.
    - At the very least, a `--non-interactive` flag (or similar) should be enabled.

### History Command
- Store metadata in the `.dodl` directory about recent activities.
- History command will allow users to retrieve details of their recent document creations and modifications 
    - This is a stretch goal that requires significant consideration.

## Contribution Guidelines

We welcome contributions from the community! If you're interested in any of these tasks, please comment here to express your interest, create a new issue if necessary, and reference this epic.

## Additional Notes

- **Testing**: Ensure all new features are thoroughly tested.
- **Documentation**: Update documentation to reflect new and modified features.

**Comment by matthewchivers** [comment]
Probably to be released in a minor version, but other functionality to consider:
* Allow common directories
   * Allow a common directory to be specified in config and then used by document types
* Allow parent docs / inheritance?
   * For example, I might have a "note" doctype. I'd like to create a new "projectX" docType using the same directory template, filename template, and actual doc template as "note" but with "topic" always set to "projectX". 
   * If I could specify "note" as something to inherit from / be the parent, that would probably work nicely. 
   * That said, terminology is important. Parent might imply that this document goes "within" the parent directory rather than mimicking the parent document.
   * Perhaps set an "override" field with a document to be overridden with whatever settings are here, when this doctype is used?
* Allow one document to "trigger" another. e.g. If I input a "vacation-day" document for a particular date, that could also create a "daily standup" document for that day stating "I was on vacation on this date - didn't attend standup".
    * This might also be useful for "follow up tasks" documents to be created for a specific meeting type, or "goals" document to be created after a "manager-1-2-1" or whatnot.
* Add ability to return whether a file has been created or was already present (UX feedack peace of mind for user)
* Consider ability to set ranges (such as date) to create multiple documents at once.
* Autocomplete
    * Perhaps goes hand in hand with some of the history stuff above (or at least, the goals of the history command)
    * Want to be able to start typing the name of a document type and have it tab-complete, or even provide a list of options if there are some.

**Comment by matthewchivers** [comment]
I don't think this is accurate. I think semantic versioning will take over in a slightly different way. I had ancitipated:
* 0.1.0
* 0.2.0
* ...
* 0.9.0
* 1.0.0
etc.
However I think it's likely we will see
* 0.1.0
* 0.2.0
* 0.2.1
* ...
* 0.9.0
* 0.10.0
* 0.11.0 // 11 comes after 10...
etc.

Or maybe even
* 0.7.0
* 1.0.0 // skipping 0.8.0 etc. because there is a breaking change and that means it's time for a major release.
* 1.1.0

The bulletpoints in this issue have been converted into separate issues, and this "epic" will be closed.
